"""OpenProp public API."""

from .association import (
    AssociationAuditLedger,
    AssociationCandidate,
    AssociationPolicy,
    EntityAssociationHypothesis,
    MultiEntityAssociator,
    VISUAL_DETECTION_SCHEMA,
    VLMPropertyDetector,
    VisualPropertyDetection,
)
from .association_benchmark import (
    ASSOCIATION_CONDITIONS,
    AssociationBenchmarkCase,
    AssociationBenchmarkSplit,
    AssociationCalibrationResult,
    AssociationEvaluation,
    association_benchmark_registry,
    association_benchmark_split,
    calibrate_association_policy,
    default_association_benchmark_associator,
    evaluate_association,
)
from .ai2thor_adapter import (
    AI2ThorFrameBundle,
    AI2ThorObjectTruth,
    AI2ThorPropertyChange,
    AI2ThorTransitionTruth,
    ai2thor_property_registry,
    derive_ai2thor_transition,
    extract_ai2thor_frame,
    normalize_ai2thor_regions,
)
from .ai2thor_capture import (
    CAPTURE_TRUTH_BOUNDARY,
    prepare_ai2thor_capture_manifest,
    resolve_capture_artifact,
    verify_ai2thor_capture_manifest,
)
from .ai2thor_protocol import (
    AI2THOR_SCENE_SPLIT_PROTOCOL,
    DEFAULT_AI2THOR_SPLIT_SEED,
    build_ai2thor_scene_split,
    default_ai2thor_scene_catalog,
    write_ai2thor_scene_split,
)
from .comparators import ComparatorRegistry, default_comparators
from .llm import (
    JSONLLMClient,
    LLMError,
    LLMQueryParser,
    OpenAIResponsesClient,
    ParsedQuery,
    QUERY_FRAME_SCHEMA,
)
from .global_assignment import GlobalOneToOneAssociator
from .matcher import EntityMatcher
from .query_decision import (
    FrozenQueryAcceptancePolicy,
    QueryDecision,
    QueryDecisionPolicy,
    apply_query_acceptance_policy,
    build_visual_query_result,
    calibrate_query_acceptance_policy,
    decide_query_match,
)
from .models import (
    ComparisonResult,
    Entity,
    EntityEvent,
    MatchResult,
    Observation,
    ObservationState,
    PropertyConstraint,
    PropertyDefinition,
    PropertyUpdatePolicy,
    QueryFrame,
    RelationValue,
    TemporalPolicy,
    ValueType,
)
from .open_world_adaptation import (
    CALIBRATED_NOVEL_SUBJECT,
    OPEN_WORLD_ADAPTATION_CONDITIONS,
    OPEN_WORLD_PAIRWISE_PARTITIONS,
    OPEN_WORLD_TRIPLE_PARTITIONS,
    SOURCE_SEEN,
    TARGET_CALIBRATED_NOVEL,
    TARGET_UNCALIBRATED_NOVEL,
    UNCALIBRATED_NOVEL_SUBJECT,
    OpenWorldAdaptationDataset,
    open_world_adaptation_data,
)
from .observation_history import (
    ObservationHistoryRecord,
    PersistenceDataSplit,
    grouped_split,
    history_to_examples,
    read_history_jsonl,
    write_history_jsonl,
)
from .ollama import OllamaClient
from .persistence import ExponentialPersistenceModel, PersistenceModel
from .persistence_data import PersistenceTrainingExample
from .property_registry import PropertyRegistry, Resolution
from .selectors import MentionBasedSelector, PropertySelector, SelectedProperty
from .survival_evaluation import (
    HorizonCalibration,
    SurvivalEvaluation,
    evaluate_survival,
)
from .teach_adapter import (
    DEFAULT_TEACH_STATE_PROPERTIES,
    TeachReplay,
    TeachReplaySnapshot,
    apply_teach_state_diff,
    read_teach_replay,
    reconstruct_teach_snapshots,
    teach_hidden_current_truth,
    teach_visible_observation_history,
)
from .teach_dialogue_alignment import (
    TEACH_DIALOGUE_ALIGNMENT_POLICY_ID,
    TEACH_DIALOGUE_ALIGNMENT_SAMPLE_SEED,
    TeachDialogueAlignmentCase,
    TeachDialogueTurn,
    align_teach_game_dialogue,
    audit_teach_dialogue_alignments,
    build_teach_dialogue_alignment_label_template,
    freeze_teach_dialogue_alignment_sample,
    teach_manifest_sha256,
    write_teach_dialogue_alignment_json,
)
from .teach_feasibility import (
    TeachFeasibilityCriteria,
    assign_teach_floorplan_splits,
    evaluate_teach_feasibility,
    read_teach_dialogue_alignment_audit,
)
from .teach_experiment import (
    TeachExperimentPartition,
    TeachPreparedExperiment,
    prepare_teach_layer_b_experiment,
    run_teach_layer_b_experiment,
    write_teach_layer_b_report,
)
from .teach_grounding import (
    TEACH_BOOLEAN_STATE_PROPERTIES,
    audit_teach_grounding_cases,
    build_teach_gold_grounding_cases,
    teach_grounding_registry,
)
from .teach_layer_c import (
    TeachLayerCPrepared,
    prepare_teach_layer_c_cases,
    validate_teach_layer_c_gate,
)
from .teach_layer_c_annotation import (
    TEACH_LAYER_C_ANNOTATION_PROTOCOL_ID,
    TEACH_LAYER_C_MIN_PAIRWISE_AGREEMENT,
    TeachLayerCAnnotationResolution,
    apply_teach_layer_c_annotation_resolution,
    build_teach_layer_c_annotation_template,
    resolve_teach_layer_c_annotations,
)
from .target_adaptation import (
    LogRiskAffineAdapter,
    TargetCalibrationProtocol,
    build_target_calibration_protocol,
    fit_log_risk_affine_adapter,
    select_sign_gated_model,
)
from .target_adaptation_stress import (
    FeatureGroupedSignGatedModel,
    STRESS_CONDITIONS,
    TargetAdaptationStressDataset,
    corrupt_calibration_event_labels,
    fit_confirmed_feature_grouped_sign_gate,
    fit_feature_grouped_sign_gate,
    target_adaptation_stress_data,
)
from .non_affine_misspecification import (
    NON_AFFINE_MISSPECIFICATION_CONDITIONS,
    LocalNonAffineRiskWarp,
    affected_contexts,
    non_affine_misspecification_models,
)
from .source_misspecification import (
    SOURCE_MISSPECIFICATION_CONDITIONS,
    MonotoneRiskTransform,
    TypedFeaturePermutationRiskModel,
    source_misspecification_models,
)
from .target_interaction_adaptation import (
    DEFAULT_TYPED_PARTITIONS,
    HierarchicalTypedInteractionGate,
    fit_hierarchical_typed_interaction_gate,
)
from .temporal_grounding import (
    NoDecayPersistenceModel,
    TemporalGroundingCase,
    TemporalGroundingReport,
    TemporalStrategy,
    evaluate_temporal_grounding,
    temporal_grounding_benchmark,
    temporal_grounding_registry,
    write_temporal_grounding_jsonl,
)
from .temporal import FreshnessResult, observation_freshness
from .vlm import (
    EntityObservationLedger,
    JSONVLMClient,
    OpenAIResponsesVLMClient,
    ParsedPropertyUpdates,
    PROPERTY_UPDATE_SCHEMA,
    PropertyUpdateProposal,
    VisualFrame,
    VLMError,
    VLMPropertyUpdater,
)
from .visual_calibration import (
    FrozenAcceptancePolicy,
    apply_acceptance_policy,
    calibrate_acceptance_policy,
)
from .visual_evaluation import (
    NULL_ENTITY,
    VisualAssociationResult,
    VisualEvaluationDataset,
    VisualPropertyResult,
    VisualQueryResult,
    aggregate_visual_evaluation,
    read_visual_results_jsonl,
    risk_coverage_curve,
    write_visual_results_jsonl,
)
from .visual_result_builder import (
    VisualDetectionEvaluationBatch,
    VisualDetectionTruth,
    VisualFrameEvaluationTruth,
    build_visual_detection_results,
)
from .vlm_replay import read_captured_vlm_response, write_captured_vlm_response
from .visual_pipeline import (
    EntityStateStore,
    VisualFrameUpdate,
    VisualUpdateOrchestrator,
    VisualUpdateRun,
)
from .visual_replay import VisualReplayOutcome, replay_visual_case
from .visual_replay_evaluation import evaluate_visual_replay
from .visual_matrix import combine_visual_evaluation_datasets
from .real_video_protocol import (
    REAL_VIDEO_PROTOCOL,
    REAL_VIDEO_TRUTH_BOUNDARY,
    prepare_real_video_manifest,
    verify_real_video_manifest,
)
from .visual_statistics import paired_visual_system_comparison
from .combined_confidence import (
    FrozenCombinedConfidenceCalibration,
    FrozenIsotonicConfidence,
    apply_combined_confidence_calibration,
    fit_combined_confidence_calibration,
)
from .candidate_tracking import (
    CandidateAwareVisualOrchestrator,
    CandidateAwareVisualRun,
    CandidateSourceFrame,
    CandidateTracker,
    CandidateTrackingFrame,
    CandidateTrackingPolicy,
    CandidateTrackingRun,
    RegionProposal,
    TrackedCandidate,
)
from .candidate_evaluation import (
    CandidateFrameMetrics,
    CandidateFrameTruth,
    CandidateTrackingEvaluation,
    CandidateTruthObject,
    aggregate_candidate_tracking,
    aggregate_candidate_tracking_matrix,
    candidate_evaluation_from_mapping,
    evaluate_candidate_tracking,
)
from .candidate_replay import build_tracked_vlm_input, track_candidate_input
from .candidate_calibration import (
    CandidateCalibrationCase,
    FrozenCandidateTrackingPolicy,
    calibrate_candidate_tracking_policy,
    candidate_calibration_case_from_payloads,
    candidate_tracking_policy_from_frozen_payload,
)


__all__ = [
    "AssociationAuditLedger",
    "AssociationCandidate",
    "AssociationPolicy",
    "EntityAssociationHypothesis",
    "GlobalOneToOneAssociator",
    "MultiEntityAssociator",
    "VISUAL_DETECTION_SCHEMA",
    "VLMPropertyDetector",
    "VisualPropertyDetection",
    "ASSOCIATION_CONDITIONS",
    "AI2ThorFrameBundle",
    "AI2ThorObjectTruth",
    "AI2ThorPropertyChange",
    "AI2ThorTransitionTruth",
    "CAPTURE_TRUTH_BOUNDARY",
    "AI2THOR_SCENE_SPLIT_PROTOCOL",
    "DEFAULT_AI2THOR_SPLIT_SEED",
    "build_ai2thor_scene_split",
    "default_ai2thor_scene_catalog",
    "prepare_ai2thor_capture_manifest",
    "ai2thor_property_registry",
    "derive_ai2thor_transition",
    "extract_ai2thor_frame",
    "normalize_ai2thor_regions",
    "resolve_capture_artifact",
    "verify_ai2thor_capture_manifest",
    "write_ai2thor_scene_split",
    "FrozenAcceptancePolicy",
    "apply_acceptance_policy",
    "calibrate_acceptance_policy",
    "NULL_ENTITY",
    "VisualAssociationResult",
    "VisualEvaluationDataset",
    "VisualPropertyResult",
    "VisualQueryResult",
    "aggregate_visual_evaluation",
    "read_visual_results_jsonl",
    "risk_coverage_curve",
    "write_visual_results_jsonl",
    "read_captured_vlm_response",
    "write_captured_vlm_response",
    "VisualDetectionEvaluationBatch",
    "VisualDetectionTruth",
    "VisualFrameEvaluationTruth",
    "build_visual_detection_results",
    "EntityStateStore",
    "AssociationBenchmarkCase",
    "AssociationBenchmarkSplit",
    "AssociationCalibrationResult",
    "AssociationEvaluation",
    "association_benchmark_registry",
    "association_benchmark_split",
    "calibrate_association_policy",
    "default_association_benchmark_associator",
    "evaluate_association",
    "ComparatorRegistry",
    "ComparisonResult",
    "Entity",
    "EntityEvent",
    "EntityMatcher",
    "QueryDecision",
    "QueryDecisionPolicy",
    "FrozenQueryAcceptancePolicy",
    "apply_query_acceptance_policy",
    "build_visual_query_result",
    "calibrate_query_acceptance_policy",
    "decide_query_match",
    "ExponentialPersistenceModel",
    "FreshnessResult",
    "JSONLLMClient",
    "LLMError",
    "LLMQueryParser",
    "MatchResult",
    "MentionBasedSelector",
    "Observation",
    "ObservationState",
    "OllamaClient",
    "OpenAIResponsesClient",
    "ParsedQuery",
    "PropertyConstraint",
    "PropertyDefinition",
    "PropertyUpdatePolicy",
    "EntityObservationLedger",
    "JSONVLMClient",
    "OpenAIResponsesVLMClient",
    "ParsedPropertyUpdates",
    "PROPERTY_UPDATE_SCHEMA",
    "PropertyUpdateProposal",
    "VisualFrame",
    "VLMError",
    "VLMPropertyUpdater",
    "PropertyRegistry",
    "VisualFrameUpdate",
    "VisualUpdateOrchestrator",
    "VisualUpdateRun",
    "VisualReplayOutcome",
    "replay_visual_case",
    "evaluate_visual_replay",
    "combine_visual_evaluation_datasets",
    "REAL_VIDEO_PROTOCOL",
    "REAL_VIDEO_TRUTH_BOUNDARY",
    "prepare_real_video_manifest",
    "verify_real_video_manifest",
    "paired_visual_system_comparison",
    "FrozenCombinedConfidenceCalibration",
    "FrozenIsotonicConfidence",
    "apply_combined_confidence_calibration",
    "fit_combined_confidence_calibration",
    "CandidateAwareVisualOrchestrator",
    "CandidateAwareVisualRun",
    "CandidateSourceFrame",
    "CandidateTracker",
    "CandidateTrackingFrame",
    "CandidateTrackingPolicy",
    "CandidateTrackingRun",
    "RegionProposal",
    "TrackedCandidate",
    "CandidateFrameMetrics",
    "CandidateFrameTruth",
    "CandidateTrackingEvaluation",
    "CandidateTruthObject",
    "aggregate_candidate_tracking",
    "aggregate_candidate_tracking_matrix",
    "candidate_evaluation_from_mapping",
    "evaluate_candidate_tracking",
    "build_tracked_vlm_input",
    "track_candidate_input",
    "CandidateCalibrationCase",
    "FrozenCandidateTrackingPolicy",
    "calibrate_candidate_tracking_policy",
    "candidate_calibration_case_from_payloads",
    "candidate_tracking_policy_from_frozen_payload",
    "PropertySelector",
    "PersistenceModel",
    "QueryFrame",
    "QUERY_FRAME_SCHEMA",
    "RelationValue",
    "TemporalPolicy",
    "Resolution",
    "SelectedProperty",
    "ValueType",
    "CALIBRATED_NOVEL_SUBJECT",
    "OPEN_WORLD_ADAPTATION_CONDITIONS",
    "OPEN_WORLD_PAIRWISE_PARTITIONS",
    "OPEN_WORLD_TRIPLE_PARTITIONS",
    "SOURCE_SEEN",
    "TARGET_CALIBRATED_NOVEL",
    "TARGET_UNCALIBRATED_NOVEL",
    "UNCALIBRATED_NOVEL_SUBJECT",
    "OpenWorldAdaptationDataset",
    "open_world_adaptation_data",
    "default_comparators",
    "ObservationHistoryRecord",
    "PersistenceDataSplit",
    "PersistenceTrainingExample",
    "HorizonCalibration",
    "SurvivalEvaluation",
    "grouped_split",
    "history_to_examples",
    "read_history_jsonl",
    "write_history_jsonl",
    "evaluate_survival",
    "DEFAULT_TEACH_STATE_PROPERTIES",
    "TEACH_DIALOGUE_ALIGNMENT_POLICY_ID",
    "TEACH_DIALOGUE_ALIGNMENT_SAMPLE_SEED",
    "TeachDialogueAlignmentCase",
    "TeachDialogueTurn",
    "align_teach_game_dialogue",
    "audit_teach_dialogue_alignments",
    "build_teach_dialogue_alignment_label_template",
    "freeze_teach_dialogue_alignment_sample",
    "teach_manifest_sha256",
    "write_teach_dialogue_alignment_json",
    "TeachReplay",
    "TeachReplaySnapshot",
    "TeachFeasibilityCriteria",
    "TEACH_BOOLEAN_STATE_PROPERTIES",
    "assign_teach_floorplan_splits",
    "evaluate_teach_feasibility",
    "NON_AFFINE_MISSPECIFICATION_CONDITIONS",
    "LocalNonAffineRiskWarp",
    "affected_contexts",
    "non_affine_misspecification_models",
    "SOURCE_MISSPECIFICATION_CONDITIONS",
    "MonotoneRiskTransform",
    "TypedFeaturePermutationRiskModel",
    "source_misspecification_models",
    "read_teach_dialogue_alignment_audit",
    "audit_teach_grounding_cases",
    "build_teach_gold_grounding_cases",
    "apply_teach_state_diff",
    "TeachExperimentPartition",
    "TeachPreparedExperiment",
    "prepare_teach_layer_b_experiment",
    "run_teach_layer_b_experiment",
    "write_teach_layer_b_report",
    "teach_grounding_registry",
    "TeachLayerCPrepared",
    "prepare_teach_layer_c_cases",
    "validate_teach_layer_c_gate",
    "TEACH_LAYER_C_ANNOTATION_PROTOCOL_ID",
    "TEACH_LAYER_C_MIN_PAIRWISE_AGREEMENT",
    "TeachLayerCAnnotationResolution",
    "apply_teach_layer_c_annotation_resolution",
    "build_teach_layer_c_annotation_template",
    "resolve_teach_layer_c_annotations",
    "read_teach_replay",
    "reconstruct_teach_snapshots",
    "teach_hidden_current_truth",
    "teach_visible_observation_history",
    "NoDecayPersistenceModel",
    "TemporalGroundingCase",
    "LogRiskAffineAdapter",
    "TargetCalibrationProtocol",
    "build_target_calibration_protocol",
    "fit_log_risk_affine_adapter",
    "select_sign_gated_model",
    "STRESS_CONDITIONS",
    "FeatureGroupedSignGatedModel",
    "TargetAdaptationStressDataset",
    "corrupt_calibration_event_labels",
    "fit_confirmed_feature_grouped_sign_gate",
    "fit_feature_grouped_sign_gate",
    "target_adaptation_stress_data",
    "DEFAULT_TYPED_PARTITIONS",
    "HierarchicalTypedInteractionGate",
    "fit_hierarchical_typed_interaction_gate",
    "TemporalGroundingReport",
    "TemporalStrategy",
    "evaluate_temporal_grounding",
    "temporal_grounding_benchmark",
    "temporal_grounding_registry",
    "write_temporal_grounding_jsonl",
    "observation_freshness",
]
